spring:
  application:
    name: roomo-backend
  
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres
    username: postgres.rvavffrowjxpqeifwdjs
    password: root
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

# Auth0/Okta OAuth2 Configuration
okta:
  oauth2:
    # Replace with your Auth0 domain (e.g., https://your-domain.auth0.com/)
    issuer: https://dev-zziz4u00lzvpcrq5.us.auth0.com/
    # Replace with your API Identifier from Auth0
    audience: https://api.roomo.com

server:
  port: 8080

logging:
  level:
    com.roomo: DEBUG
    org.springframework.security: DEBUG 
