spring:
  application:
    name: roomo-backend

  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres
    username: postgres.rvavffrowjxpqeifwdjs
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  # Multipart file upload configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

# Auth0/Okta OAuth2 Configuration
okta:
  oauth2:
    # Replace with your Auth0 domain (e.g., https://your-domain.auth0.com/)
    issuer: https://dev-zziz4u00lzvpcrq5.us.auth0.com/
    # Replace with your API Identifier from Auth0
    audience: https://api.roomo.com

# Auth0 Management API Configuration
auth0:
  management:
    domain: ${AUTH0_DOMAIN:dev-zziz4u00lzvpcrq5.us.auth0.com}
    client-id: ${AUTH0_MANAGEMENT_CLIENT_ID:VQlYLDanTZRupm1IH1rzFugLvl6hR44d}
    client-secret: ${AUTH0_MANAGEMENT_CLIENT_SECRET:q_uO8B9axZHqDutBwtq9dXci-yTHy0eWdkN4reev-87aqH-TdAZUXH4n6NF4ExLi}
    audience: https://${auth0.management.domain}/api/v2/
    token-cache-duration: 3600

# Supabase Configuration
supabase:
  url: https://rvavffrowjxpqeifwdjs.supabase.co
  anon-key: ${SUPABASE_ANON_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2YXZmZnJvd2p4cHFlaWZ3ZGpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNDYyMjEsImV4cCI6MjA2NjgyMjIyMX0.OaCKyBXqRYKVDUHM6YdRK9wFmjHYHbWggmCu3KOyceY}
  storage:
    bucket-name: roomo-images
    max-file-size: 5242880  # 5MB in bytes
    allowed-mime-types:
      - image/jpeg
      - image/png
      - image/gif
      - image/webp

server:
  port: 8080

logging:
  level:
    com.roomo: DEBUG
    org.springframework.security: DEBUG
